table AMZN
	lineageTag: 85345cf4-0910-44c4-b603-f0c920022f5a

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 38991c4d-8bb2-4388-91fe-00a687a678a9
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fa15a675-208c-4444-9570-282419ac0402
			defaultHierarchy: LocalDateTable_d2f537fe-20c8-4279-a23e-8b41fcfc3430.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 2142d4d9-7e54-460b-ac96-80f5af90b90b
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 4241cca3-db09-4001-ba82-45fc9c914669
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: b1986796-ff16-491f-89a0-5535e4826ca7
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 4f1f114b-1ddf-4069-8770-874e34b5133d
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: e77e7af5-eae9-43b6-89ad-d043de01211d
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: c1c18cdc-dcbd-47a9-ac75-cd609ce95a3d
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\rwang\OneDrive - Wallick Communities\Desktop\Reports\Learn Python\PowerBI Source Control\PBIBroPBISourceControl\AMZN.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

